### ISSUE TITLE
Tree arrow reverse back to father node when creating child node of the same value with father node

### ISSUE THREAD

**Issue by trandat9h** [dangchinh25/ds-visualizer#1] opened 2022-01-30 15:51 UTC
Check this test case : [3, 9, 20, -2, 3, 15, 7, 8]
This test should create new child node of value 3 instead of arrow back to father of value 3

**Comment by dangchinh25** [comment] 2022-01-31 06:22
Thank you for your suggestion. This was by design as I didn't plan to allow duplicating value in BinaryTree at first. This has been fixed in version 1.0.5.

**Closed by dangchinh25** 2022-01-31 06:22 UTC
Labels: enhancement
